In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow 
from tensorflow import keras
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.models import Sequential

In [2]:
df = pd.read_csv('Booking.csv')
df.sample(10)

,Booking_ID,number of adults,number of children,number of weekend nights,number of week nights,type of meal,car parking space,room type,lead time,market segment type,repeated,P-C,P-not-C,average price,special requests,date of reservation,booking status
13843,INN13844,2,0,0,3,Meal Plan 1,0,Room_Type 1,104,Offline,0,0,0,75.00,0,12/3/2017,Not_Canceled
520,INN00521,1,0,2,1,Meal Plan 1,0,Room_Type 4,7,Online,0,0,0,85.85,1,3/5/2018,Not_Canceled
10799,INN10800,2,0,2,1,Meal Plan 1,0,Room_Type 1,40,Online,0,0,0,112.50,1,8/28/2018,Not_Canceled
27642,INN27643,2,0,1,0,Meal Plan 1,0,Room_Type 1,0,Offline,0,0,0,111.20,0,9/14/2017,Not_Canceled
30041,INN30042,2,0,1,2,Meal Plan 1,0,Room_Type 1,22,Online,0,0,0,76.81,0,9/4/2017,Not_Canceled
4141,INN04142,2,1,1,0,Meal Plan 1,0,Room_Type 1,0,Online,0,0,0,127.00,0,6/26/2018,Not_Canceled
20571,INN20572,3,0,2,1,Meal Plan 1,0,Room_Type 4,61,Offline,0,0,0,90.00,0,11/21/2017,Not_Canceled
4380,INN04381,2,0,0,1,Not Selected,0,Room_Type 1,113,Online,0,0,0,108.00,1,10/13/2018,Canceled
4243,INN04244,2,0,1,0,Not Selected,0,Room_Type 1,0,Online,0,0,0,90.00,1,8/1/2018,Not_Canceled
23054,INN23055,2,2,1,2,Meal Plan 1,0,Room_Type 6,1,Online,0,0,0,211.76,1,10/28/2018,Not_Canceled